[14.0] Add connector_importer_product
OCA/connector-interfaces pull request #88
Opened 2022-03-07 16:03 UTC by mmequignon

Base product importer, with SFTP support

2022-03-08 08:44 UTC, simahawk commented on connector_importer_product/readme/DESCRIPTION.rst
> +Generic module to import product throught SFTP
is not for SFTP only

2022-03-08 14:27 UTC, sebalix commented on connector_importer_product/data/import_recordset.xml
> +    <field name="source_model">import.source.csv.sftp</field>
Should not be tied to SFTP only
```suggestion
    <field name="source_model">import.source.csv.sftp</field>
```

2022-03-08 14:28 UTC, sebalix commented on connector_importer_product/data/import_source.xml
> +    <field name="move_file_after_import" eval="1" />
This is also a configuration brought by SFTP, to remove I guess

2022-03-09 07:43 UTC, TDu reviewed
About my comment of the class name I just stopped after a while of reviewing, I means it is not that important

2022-03-09 07:43 UTC, TDu commented on connector_importer_product/__manifest__.py
> +        # Demo
```suggestion
```

2022-03-09 07:43 UTC, TDu commented on connector_importer_product/components/common.py
> +        """Overridden to handle 'name_fr' and 'name_de' fields."""
Need to be reformulated it is not specific to fr or de, explain its use.

2022-03-09 07:43 UTC, TDu commented on connector_importer_product/components/product_attribute.py
> +class ProductAttributeRecordImporter(Component):
```suggestion
class ProductAttributeImporter(Component):
```

2022-03-09 07:43 UTC, TDu commented on connector_importer_product/components/product_attribute_value.py
> +class ProductAttributeValueRecordImporter(Component):
```suggestion
class ProductAttributeValueImporter(Component):
```

2022-03-09 07:43 UTC, TDu commented on connector_importer_product/components/product_category.py
> +class ProductCategoryRecordImporter(Component):
```suggestion
class ProductCategoryImporter(Component):
```

2022-03-09 07:43 UTC, TDu commented on connector_importer_product/components/product_packaging.py
> +class ProductPackagingRecordImporter(Component):
```suggestion
class ProductPackagingImporter(Component):
```

2022-03-31 14:22 UTC, simahawk requested changes

2022-03-31 14:22 UTC, simahawk commented on connector_importer_product/data/import_backend.xml
> +  <record id="import_backend" model="import.backend">
you should trash all these records

2022-03-31 14:22 UTC, simahawk commented on connector_importer_product/__manifest__.py
> +        "connector_importer_source_sftp",
this should not be a dependency

2022-03-31 14:22 UTC, simahawk commented on connector_importer_product/__manifest__.py
> +        "data/storage_backend.xml",
same

2022-03-31 15:45 UTC, simahawk commented
@sebalix @mmequignon I've pushed some cleanup/fixes/improvements.

2022-04-01 07:53 UTC, mmequignon reviewed
@simahawk I cannot approve my own pr, but lg.
Thx!

2022-04-01 09:24 UTC, simahawk commented
I switched tests to GH actions on #89.Rebased and squashed here.

2022-04-01 09:27 UTC, simahawk approved these changes

2022-04-04 08:27 UTC, simahawk commented
/ocabot merge minor

2022-04-04 08:30 UTC, simahawk commented
/ocabot merge minor

2022-04-04 08:34 UTC, merged